### ISSUE TITLE
Firmware: Il server non risponde al discovery dopo l'unpair

### ISSUE THREAD

**Issue by Baccega** [giulioz/IngSw2018#61]
Dopo aver fatto l'onboarding e fatto il primo pairing, se poi eseguo un unpair e provo a rifare l'onboarding il server non risponde piú al discovery e devo riavviarlo per farlo rifunzionare

**Comment by giulioz** [comment]
😢

**Comment by Baccega** [comment]
L'ho riscontrato sul mock....ovviamente sul robot non l'ho ancora potuto testare

**Comment by eleumasc** [comment]
A quanto pare, uno dei metodi della classe UI causa un errore di segmentazione e fa terminare il processo. Adesso cerco di risolvere il bug.

**Comment by eleumasc** [comment]
Non ho trovato problemi...
Dopo aver avviato il server, ho inviato in broadcast tre messaggi DOGE_SEARCH e ho ricevuto la risposta per ognuno di essi.
Ho effettuato un pairing (prima GET /pair e poi POST /pair) ed è stato effettuato con successo.
In seguito, ho inviato in broadcast un messaggio DOGE_SEARCH e ho ricevuto la risposta.
Potresti dirmi se solamente il servizio di discovery smette di funzionare oppure anche altri servizi?

**Comment by Baccega** [comment]
Forse é un problema della mia VM allora....quando ci troviamo vediamo
